### ISSUE TITLE
[Suggestion] Respect light levels

### ISSUE THREAD

**Issue by Managarmr719** [VazkiiMods/Neat#10]
It would be great if it was possible to make the health bar get darker together with the mobs, maybe make this a config option.
![2016-05-06_16 31 47](https://cloud.githubusercontent.com/assets/7836631/15077810/193ce738-13a8-11e6-9406-736ae1d20204.png)

(If you use Hardcore Darkness it's even worse. -_-')
![2016-05-06_16 23 08](https://cloud.githubusercontent.com/assets/7836631/15077639/4782d874-13a7-11e6-8f03-5ca1bbad2408.png)

**Comment by cosmicdan** [comment]
I managed to do it in a fork I made to backport some 1.7.10 stuff, see https://github.com/HostileNetworks/Neat/commit/7c7e6ccda70b8fb8c151091c48a93077292c1304

Not too difficult. The intermediate brightness levels could probably look better, but it's good enough for me (at light level 1 or 0 it is impossible to see).
![image7](https://cloud.githubusercontent.com/assets/2092676/21283929/4e2bf4e2-c461-11e6-9ce1-f192382b54b2.png)

**Comment by Uraneptus** [comment]
This is ages old omg. I will consider adding a config option for this for the newer versions
