### ISSUE TITLE
[FABRIC] Downloading this mod fixed my resource-pack

### ISSUE THREAD

**Issue by Drigonis** [VazkiiMods/Neat#101]
Not sure how. It's not exactly a bad thing - I'm glad. However, after downloading this mod it seemed to have fixed some issues with my resource pack, but also broke it. Badly.

When I joined a world, every single block texture was a teeny shrunken down version of all of the textures in Minecraft. However, when reloading my texture packs, the issue disappeared and it even fixed existing issues in my texture pack. Keep in mind I have not touched my texture pack for a while, and this was the only mod that I had just downloaded. You may want to look into the code to check there's nothing that can interfere with textures and such - or mods like CIT Resewn or Continuity.

**Comment by williewillus** [comment]
Closing as this isn't really actionable
