### ISSUE TITLE
Plates render in inventory self-view

### ISSUE THREAD

**Issue by williewillus** [VazkiiMods/Neat#102]
And probably in 3rd person too

**Comment by BakeJake** [comment]
Was wondering if it was just me
<img width="178" alt="javaw_PHOkrIywK9" src="https://user-images.githubusercontent.com/52101762/180627546-b78ca740-cb50-4a4e-964e-fee08b25955d.png">

**Comment by HgAlexx** [comment]
Strangely enough, when using shaders, it works in the inventory view too despite not working in the world :)

**Comment by Kevadroz** [comment]
This happens both in third person and when some mods do something with the render of the player (Better Combat).
I think plates shouldn't show on yourself.
