### ISSUE TITLE
Neat-1.8-31 prevents server launch

### ISSUE THREAD

**Issue by MoonMoonShark** [VazkiiMods/Neat#103]
upgraded server to Neat-1.8-31 but get a crash during load.

**Error:** `Caused by: java.lang.IllegalArgumentException: The specified resource 'neat.mixins.json' was invalid or could not be read`

**Minecraft:** 1.18.2
**Forge:** forge-1.18.2-40.1.54
**Neat:** Neat-1.8-31.jar
**Modpack:** https://www.curseforge.com/minecraft/modpacks/the-lighthouse/files/3859356

**Server Log:** https://pastebin.com/s9WDt9KG

there is no crash log, and Latest and Debug stop with no further text as soon as Neat loads.

**Comment by KatoNamus** [comment]
Same here, downgrading to 1.8-30 let my modpack load again.

**Comment by MoonMoonShark** [comment]
well, whatever the problem was, it seems to have been rectified, through a combination of updating this and other mods. so, gg team. :D
