### ISSUE TITLE
[1.19] Forge changes break this mod

### ISSUE THREAD

**Issue by jellybean13** [VazkiiMods/Neat#104]
There are two breaking changes in Forge 41.0.x:
Breaking change 1: [41.0.64](https://github.com/MinecraftForge/MinecraftForge/commit/4d074f0a1ef1d774786b4f1e1e3e827a9bf576e0).
Breaking change 2: [41.0.94](https://github.com/MinecraftForge/MinecraftForge/commit/b8b40e1f547c16df1d8914a707e338057a7497bd).
Affected classes: https://github.com/VazkiiMods/Neat/blob/master/Forge/src/main/java/vazkii/neat/NeatForgeInitializer.java#L22
This mod needs to be updated otherwise the game will crash.

**Comment by williewillus** [comment]
Fixed in 1.19-32
