### ISSUE TITLE
[BUG] health bar texture is missing or transparent when shaders are enabled

### ISSUE THREAD

**Issue by HgAlexx** [VazkiiMods/Neat#106]
mod: Neat (Fabric/Quilt)
version/file: Neat-1.19-32-FABRIC.jar

When I press k to disable or enable the shaders, the health toggle from visible to invisible.

I'm using fabric with iris and the following shader pack:
- ComplementaryShaders v4.5

I've also tested with:
- BSL v8.1.03

For both packs I've tried many settings on and off, no luck.

loader:
Fabric Loader 1.19 (0.14.8-1.19)

other mods:
- iris-mc1.19-1.2.5
- sodium-fabric-mc1.19-0.4.2build.16
- lithium-fabric-mc1.19-0.8.1
- phosphor-fabric-mc1.19.x-0.8.1
- and few other but most likely unrelated to the issue

Thank you!

**Comment by KarinMiku** [comment]
seems really similar to a bug that im experiencing on forge while using oculus, look at the issue above yours here on github

**Comment by Uraneptus** [comment]
If this is still relevant in newer versions of the mod (1.20 onwards), please open a new issue
