### ISSUE TITLE
[BUG] Neat bar moves from above the mobs to a lower corner while using shaders

### ISSUE THREAD

**Issue by KarinMiku** [VazkiiMods/Neat#107]
There seems to be a bug with Neat and in this case, oculus (iris), it seems like the fault is on oculus side, still, the first time i join the world, the mod works perfectly for like a minute before the bug happens, so maybe the fix can be done in any of both sides 

https://user-images.githubusercontent.com/51896289/180620206-29a0859c-03bc-433b-8e82-cc47503c80ad.mp4

Mods: Neat+1.7-26 / oculus-1.2.5a / rubidium-1.16.5-0.2.8
Minecraft ver: 1.16.5 / Forge 36.2.39

**Comment by noa557** [comment]
I have the exact same issue

**Comment by rom3ox** [comment]
Same here, Iris, Oculus and all the shaders tried

**Comment by Soldier874** [comment]
Hello same problem here: Minecraft 1.16.5 with Forge 36.2.39 / Neat 1.7-27 / Oculus-1.4.3 / Rubidium-0.2.10 and with the shader option OFF or all shader same problem, still not solved :/

**Comment by Soldier874** [comment]
Oh the only solution that we can offer you is to find a dev to make your fixes, I don't have that on hand and the other topic has never had a resolution to the problem, it's abberanht to close the post because it is a duplication it's like hiding the dust under the rug, aberrant...

**Comment by Soldier874** [comment]
Oh... the only solution that you can offer is to find a dev to make your fixes, I don't have that on hand and this topic has never had a resolution to the problem, it's absurd to close my most recent topic because it's is a duplication of this, it's like hiding the dust under the carpet ...

**Comment by williewillus** [comment]
The point of closing duplicates is that....there are no duplicates. We are already aware of the issue here, there is zero point in keeping another copy of it.

**Comment by Soldier874** [comment]
hmm since August this topic is dead but ok, wait for a fix 👍

**Comment by Soldier874** [comment]
I talk about a dead mod ? 🤔

**Comment by Uraneptus** [comment]
If this is still relevant in newer versions of the mod (1.20 onwards), please open a new issue
