### ISSUE TITLE
[BUG] Having this mod installed causes an xray effect.

### ISSUE THREAD

**Issue by ChadekT** [VazkiiMods/Neat#108]
I had noticed that when looking at the ground in certain angles this xray effect was present. I had removed other mods I had installed in an effort to test which of the mods is causing this. From what I could gather this mod is the reason this is happening. Has this issue been reported before?

![2022-09-19_14 46 52](https://user-images.githubusercontent.com/113884631/190965281-0cf13708-1dcb-4001-8d85-e780a3fc5b66.png)
![2022-09-19_14 46 59](https://user-images.githubusercontent.com/113884631/190965304-a5490031-2743-426a-820a-233ca74a9ac5.png)

**Comment by MoupiPics** [comment]
I think providing the mod load(i.e. Forge Fabric Quilt), your minecraft version and the version of the mod you installed might help the devs

**Comment by Uraneptus** [comment]
If this is still relevant in newer versions of the mod (1.20 onwards), please open a new issue
