### ISSUE TITLE
Forge @Mod version not actually being filled in by Gradle

### ISSUE THREAD

**Issue by Nincodedo** [VazkiiMods/Neat#11]
The mcmod.info file is being filtered for the version by Gradle but the BUILD and VERSION strings in the main class aren't due to this line https://github.com/Vazkii/Neat/blob/2930ab2f05796c887f8807bd40e00c7acbe2e0d7/build.gradle#L48

**Comment by williewillus** [comment]
No longer relevant with mods.toml
