### ISSUE TITLE
[BUG] [v32] [1.19.2] Neat Health Bars causing xray through Ice

### ISSUE THREAD

**Issue by FJDoell** [VazkiiMods/Neat#111]
Could possibly be happening with other transparent blocks as well, not sure.

![NeatBugXray](https://user-images.githubusercontent.com/102497047/196325253-5fed17cb-73eb-4522-8783-68e0517fea6c.PNG)

**Comment by krjencik** [comment]
this happens to me also with water. using minecraft 1.19.4

**Comment by Uraneptus** [comment]
If this is still relevant in newer versions of the mod (1.20 onwards), please open a new issue

Side note: having fabulous settings enabled might fix this
