### ISSUE TITLE
[Bug] [1.19-32] [Forge] Incompatibility with Rubidium + Oculus Shaders

### ISSUE THREAD

**Issue by Foozey** [VazkiiMods/Neat#112]
Type: **Bug**
Version: **1.19-32**
Modloader: **Forge**

While having Rubidium, Oculus, and Neat installed, the background and health bar plates don't render with shaders enabled. This problem is pictured below:

![2022-10-27_13 29 22](https://user-images.githubusercontent.com/68371808/198177683-33259788-ecf3-4929-a2b2-ad30eeb5d5cc.png)

**Comment by afloofflam** [comment]
Glad to know this isn't just me. Not sure if this affects it or not, but I'm using the latest Complementary shader.

**Comment by Foozey** [comment]
The shader pack itself doesn't matter, it's just having shaders enabled at all. You can be running no shader pack but have shaders enabled and still have the problem.

**Comment by Totomio** [comment]
Same here :-(

**Comment by Uraneptus** [comment]
If this is still relevant in newer versions of the mod (1.20 onwards), please open a new issue
