### ISSUE TITLE
Dynamic Max Health

### ISSUE THREAD

**Issue by NathZen** [VazkiiMods/Neat#116]
Hello, is it possible to modify the max health of an entity for above 1024?

I was using Orderly, but it was for 1.16.5 and it said it was ported from Neat. But now I'm moving to 1.19.2, which is Orderly not supported again, and I use Neat instead because this mod looks very useful. But the problem is, the health bar is capped at 1024.

Is it possible to set the max health into more than 1024?
Or maybe can you limit the max HP into 1024 instead? The bar is overflowing 😆 

![Base Profile Screenshot 2022 11 26 - 08 12 28 11](https://user-images.githubusercontent.com/61259322/204067055-dcaa8451-724f-4b50-9e95-429144846bf4.png)

![Base Profile Screenshot 2022 11 26 - 08 12 53 10](https://user-images.githubusercontent.com/61259322/204067064-6056b69d-3683-420b-9e37-accd86caa22b.png)

Thank you

**Comment by williewillus** [comment]
the maximum health an entity can have in vanilla is 1024, I'm not sure how you're getting this to happen

**Comment by williewillus** [comment]
Additionally, Neat does query the entity's max health properly (it's not hardcoded):
https://github.com/VazkiiMods/Neat/blob/a46ab527f9611819392a91eb924712701bbf3296/Xplat/src/main/java/vazkii/neat/HealthBarRenderer.java#L220

In this case an entity somehow has a current health higher than its max health, though I guess we can handle that better.
