### ISSUE TITLE
The HUD added by the mod shows to low

### ISSUE THREAD

**Issue by Aeldit** [VazkiiMods/Neat#118]
![2022-12-13_14 51 56](https://user-images.githubusercontent.com/81476169/207346704-7c277fc3-a0fc-411e-8690-3736dbad8bf2.png)

As you can see on the image, it doesn't show correctly. The same happens with other mobs

**Comment by BillyGalbreath** [comment]
I fixed this by opening the config file (neat-client.json5) and changing the `heightAbove` value from `0` to `0.5`
