### ISSUE TITLE
Crashes dedicated servers due to class loading

### ISSUE THREAD

**Issue by ChiefArug** [VazkiiMods/Neat#125]
Other client side only mods such as Mouse Tweaks just gracefully dont load instead of crashing the server.
Its incredibly annoying when you are trying to quickly start up a server to test smthn and you have to go through an extra three or four boot cycles to weed out bad client side mods.

Crash report: https://gist.github.com/ChiefArug/af57437af8684a074f78720b095a78c0
Forge, 1.19.2, Neat version 1.19-32

**Comment by C0rn3j** [comment]
https://github.com/tr7zw/3d-Skin-Layers/issues/87

Not the only mod with this issue unfortunately
