### ISSUE TITLE
Configureable with Fabric's Modmenu mod

### ISSUE THREAD

**Issue by Dannydads** [VazkiiMods/Neat#126]
I know the mod says it's highly configurable on the download page, but uh... I cant' seem to figure out how to configure it at all. It would be awesome if it would show up in the Modmenu mod a lot of other mods can use. I'd like to disable the creature's name, and the text on the health bar, leaving only the bar hanging above their heads.

**Comment by fourthhouse** [comment]
yeah it says very configurable but i dont see a single config file. Can't figure out why it's showing me the creature ID under the health bar 
"Pig" 
"Health"
"Id: Pig" 
 where is the configuration in this "highly configurable" mod? tired of this

**Comment by williewillus** [comment]
> where is the configuration in this "highly configurable" mod?

In the config folder of the instance, like every mod has done for the past 12 years

> tired of this

and I'm tired of unproductive snark and no one volunteering to step up and do the work

**Comment by williewillus** [comment]
![image](https://github.com/VazkiiMods/Neat/assets/2015032/dd3fe9cf-ef08-45ba-9c45-06b9724cbb4b)
