### ISSUE TITLE
Feature request: Add an option to make health bars only show up when a mob is damaged

### ISSUE THREAD

**Issue by ionlyusegithubformcmods** [VazkiiMods/Neat#130]
Feature request: Add an option to make health bars only show up when a mob is damaged
Its kind of awkward seeing the health bars over every mob constantly, and I think a good solution to that would be to add an option making health bars only show up when a mob is damaged for a short period of time.

**Comment by williewillus** [comment]
This already exists, turn the `showFullHealth` option on Fabric or the `Show entities with full health` option on Forge to false and mobs with full health will stop showing the bars
