### ISSUE TITLE
crash on mc 1.20

### ISSUE THREAD

**Issue by Devilswarchild** [VazkiiMods/Neat#133]
Crashing During bootup sequence before I even get to the main menu.

Minecraft Version: 1.20
Forge Version: 46.0.14

[launcher_log](https://mclo.gs/tD1G4KZ)

[debug](https://mclo.gs/LUPu120)

[latest](https://mclo.gs/x0YfQyp)

[crash report](https://mclo.gs/kkLJg2R)

Current Modlist:

[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)

[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)

[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)

[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)

[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)

[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)

[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)

[Ambient Environment (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ambient-environment)

[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)

[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)

[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)

[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)

[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

[Exotelcraft (by TKD_Kedis)](https://www.curseforge.com/minecraft/mc-mods/exotelcraft)

[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)

[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)

[Rubidium Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)

[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)

[Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/cha-s)

[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)

[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)

[Macaw's Fences - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-biomes-o-plenty)

[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)

[Ash API (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/ash-api)

[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)

[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)

[Falling Leaves (Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)

[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)

[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)

[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)

[Immersive Structures II: Nether edition (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures-ii-nether-edition)

[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)

[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)

[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)

[Ultris: Boss Expansion (by limesplatus)](https://www.curseforge.com/minecraft/mc-mods/ultris-boss-expansion)

[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)

[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)

[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)

[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)

[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)

[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)

[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)

[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)

[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)

[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)

[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)

[VillagersPlus (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/villagersplus-forge)

[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)

[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)

[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)

[TieFix (by j_t_a_i)](https://www.curseforge.com/minecraft/mc-mods/tiefix)

[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)

[Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)

[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)

[Visual Overhaul (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/visual-overhaul)

[Armourer's Workshop (by RiskyKen)](https://www.curseforge.com/minecraft/mc-mods/armourers-workshop)

[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)

[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)

[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)

[Leaves Be Gone (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)

[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)

[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)

[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)

[Borderless Window (by nekeras)](https://www.curseforge.com/minecraft/mc-mods/borderless)

[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)

[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)

**Comment by williewillus** [comment]
mixin conflict with Exotelcraft.

Unfortunately, that mod is not open source, making investigation impossible. There's nothing we can do here.

**Comment by williewillus** [comment]
Mods should not be doing @Overwrite, it's incredibly uncomposable. While I can move the Neat mixin injection somewhere else (I haven't verified whether it's actually safe as that person says), who's to say some other mod won't overwrite that method too?

Additionally, IMO the onus is on the author of the closed-source mod to be compatible with the ecosystem, not the other way around.

**Comment by Uraneptus** [comment]
I will close this since it's a year old!
