### ISSUE TITLE
[Feature Request] Displaying Mob Levels

### ISSUE THREAD

**Issue by xyxt1c** [VazkiiMods/Neat#134]
It would be a nice addition if neat could display mob levels like in the [Nameplate Mod](https://modrinth.com/mod/nameplate) with small configuration options. When playing with mods that add difficulty over time it's nicer to have a level next to the health bar.

**Comment by Uraneptus** [comment]
This seems like a too niche addition imo. It would only serve a few players that have RPG difficulty installed and it would only work for fabric. If there were more mods that added such level systems, I'd need to handle each mod differently, which sounds like too much effort for such a simple feature.
I think I wanna stick to vanilla data displaying for now
