### ISSUE TITLE
Name tag vanilla

### ISSUE THREAD

**Issue by luchothv** [VazkiiMods/Neat#136]
Hi, i have a question/issue. Is possible disable the name tag vanilla ? Using "Neat" still appears and show both like the image. Thanks ! Im in 1.18.2 - Java Edition
![Sin título](https://github.com/VazkiiMods/Neat/assets/15499176/0568d6bb-3793-4013-b313-603bf28a4a85)

**Comment by Uraneptus** [comment]
Added
