### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by Slooshie1** [VazkiiMods/Neat#140]
The latest version that works on 1.20.1 crashes the game upon loading into a server on 1.20.2

**Comment by QuentiumYT** [comment]
Really need that please

**Comment by Kithron** [comment]
Any updates on this? It still crashes with 1.20.2

**Comment by MC-luoluo** [comment]
1.20.4 has been released, but this mod still does not support 1.20.2

**Comment by solos1972** [comment]
> 1.20.4 has been released, but this mod still does not support 1.20.2

where?
can you send me the link?

**Comment by solos1972** [comment]
> 1.20.4 has been released, but this mod still does not support 1.20.2

where?
can you send me the link?

**Comment by MC-luoluo** [comment]
> > 1.20.4 has been released, but this mod still does not support 1.20.21.20.4已经发布，但是这个mod仍然不支持1.20.2
> 
> where? 在哪里？ can you send me the link?你能把链接发给我吗？

sorry, i mean Minecraft 1.20.4 is released
