### ISSUE TITLE
crash on mc 1.20.4 by entity of squid/glow_squid

### ISSUE THREAD

**Issue by IrisSundew** [VazkiiMods/Neat#144]
![01](https://github.com/VazkiiMods/Neat/assets/45328260/d55b3ff3-3c10-4405-9384-743404cbaaac)
![02](https://github.com/VazkiiMods/Neat/assets/45328260/3fb510db-3b0a-4460-933a-790af1f46bd7)

**Comment by Uraneptus** [comment]
There is no version uploaded that is compatible with 1.20.4
