### ISSUE TITLE
Feature Request: Reposition Armor and type icons

### ISSUE THREAD

**Issue by Awec4** [VazkiiMods/Neat#156]
(1.20.1) I'm using the AutoLevelling mod to add Levels to mobs, however on the Neat unit frame the level is displayed in the same position as the Armor and Unit type icons, causing them to overlap. It would be nice to have the option to add an offset to the icons, which would fix this issue without needing specific compatibility between the mods.

**Comment by Uraneptus** [comment]
I currently don't have the time to do this, so I'd advise just disabling the icons for now! I
 will revisit this at a later time.

**Comment by Fydar** [comment]
Here is the configuration you can use to disable the "Attributes" (mob type) and "Armor" icons.

`config\neat-client.toml`
```ini
[general]
    # ...
    "Show Attributes" = false
    "Show Armor" = false
    # ...
```

**Comment by Uraneptus** [comment]
added and will be released soon
