### ISSUE TITLE
Crash when breaking ars-nouveau containment jars and openblocks trophies.

### ISSUE THREAD

**Issue by Gaz492** [VazkiiMods/Neat#157]
Not entirely sure who's to blame for this crash, but when breaking a containment jar with a captured mob such as a blaze or camel, or an openblocks trophies such as the wither trophy, the game will run into a crash if you also have the mod neat installed.

In both cases disabling neat stopped the crashes from happening.

Neat + Ars-nouveau Crash log: https://pste.me/@1xvU6C1e7ss
Neat + Openblocks trophies: https://pste.me/@XGZqU-eIG3U

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5808
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5790
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5846

**Comment by Uraneptus** [comment]
Thanks for reporting this. I will take a look at this today!

**Comment by Uraneptus** [comment]
This commit: e7e52b764bef77414e1c721b26c5854b660d5d35 should fix this. I will close this issue when I release the update in a few days
