### ISSUE TITLE
Expose HEALTH_FORMAT in Configuration

### ISSUE THREAD

**Issue by Fydar** [VazkiiMods/Neat#159]
Allow the decimal format to be configured. 

https://github.com/VazkiiMods/Neat/blob/d9150fe75d356a2802e0ebcfb5f272aeb979d6ee/Xplat/src/main/java/vazkii/neat/HealthBarRenderer.java#L39

I want to be able to remove the decimal points and round up. I'm rather dyslexic and the pixel art font that Minecraft uses isn't exactly perfect for dyslexia. The less numbers, the easier it would be to scan. The decimal point is often hard to see and the additional information isn't important to me.

**Comment by Uraneptus** [comment]
added and will be released soon
