### ISSUE TITLE
[Feature?] Nametag Rendering Disables Players Too

### ISSUE THREAD

**Issue by Fyoncle** [VazkiiMods/Neat#163]
As the title states, if vanilla nametag rendering disabled, it also disables player names instead of only animals. Which is if you wanna get rid of the vanilla nametag only because Neat displaying it for them (i have players disabled) it will also hide it for the player.

It would be nice if it was a seperate config or not a thing at all.

**Comment by Uraneptus** [comment]
Oh that's interesting and def not intended. I'll get a fix out soon!

**Comment by Fyoncle** [comment]
> Oh that's interesting and def not intended. I'll get a fix out soon!

Thanks! I use 1.20.1 Fabric if that helps

**Comment by ItsShamed** [comment]
I think I got a patch working should I PR it?

![2024-10-20_13 32 44](https://github.com/user-attachments/assets/367fbd93-3515-4f7c-88bb-6c7bbbef05fc)

**Comment by Fyoncle** [comment]
It seems like hiding the Neat by the keybind also doesn't return the vanilla nametag rendering but instead HIDE EVERYTHING

**Comment by ItsShamed** [comment]
Something like this?

https://github.com/user-attachments/assets/628364f7-0ead-422c-a55d-379bca14cb34

**Comment by Uraneptus** [comment]
Already got an uncomitted fix, but I wanna test a few more things first

**Comment by Uraneptus** [comment]
added and will be released soon

**Comment by Fyoncle** [comment]
> added and will be released soon

Much appreciated ❤️
