### ISSUE TITLE
[Suggestion] New config option: "Show Entity Name"

### ISSUE THREAD

**Issue by ulk-underscore** [VazkiiMods/Neat#19]
The name gets redundant with mods like The One Probe and Lycanite's Mobs Soulgazer. Plus it looks weird with [some mod's entity names](http://imgur.com/a/KZSsO).

**Comment by Alaberti** [comment]
Did this ever get any traction? Would really love to have this option, and it looks like you already did most if not all of the work? @Vazkii since this has been here this long, is it safe to say there's no interest/bandwidth in this tweak? Or was it just forgotten after uh...4ish years oh lol

**Comment by Uraneptus** [comment]
This did exist in an old version. It seems to have been lost somehow. I will readd this for newer versions.
