### ISSUE TITLE
[Suggestion] Allow us to configure names for mods that don't give proper names.

### ISSUE THREAD

**Issue by KaneHart** [VazkiiMods/Neat#20]
It would be nice if we could have a debug option to see their exact names and then a config option where we can replace their names. 

Example: https://i.imgur.com/ZSoHdA9.png

Maybe I could in the config add entity.BiomesOPlenty.butterfly.name = Butterfly

Not sure if wildcards and such could be possible too.

Thanks :)

**Comment by Uraneptus** [comment]
Can you confirm this is still an issue in newer versions and open a new issue then?
