### ISSUE TITLE
Mobs sometimes lose health bars after player travels through nether portal

### ISSUE THREAD

**Issue by Ulysses2** [VazkiiMods/Neat#21]
Minecraft Version: 1.10.2
Operating System: Mac OS X (x86_64) version 10.11.6
Java Version: 1.8.0_74, Oracle Corporation
Forge version: 12.18.0.2007
Mod list: Neat 1.3-12

Sometimes after the player goes through a portal, existing mobs in the area will not show health bars. If new mobs are spawned, they will get health bars even if other mobs still do not have them.
![2016-11-21_22 20 03](https://cloud.githubusercontent.com/assets/9127495/20509757/f8cc1f40-b038-11e6-90ff-28d8349cd5a9.png)

**Comment by Uraneptus** [comment]
If this is still relevant in the newer versions, please open a new issue
