### ISSUE TITLE
Doesn't render well with shaders.

### ISSUE THREAD

**Issue by pirone2** [VazkiiMods/Neat#31]
It doesn't show the background or the bar itself well when using shaders.
It only renders when facing the mob from specific directions.
The text renders just fine all the time.

**Comment by Hellzbellz123** [comment]
did you ever find a fix for this?

**Comment by outpoints** [comment]
Did you? @Hellzbellz123

**Comment by starlingfire** [comment]
FYI @Hellzbellz123, @outpoints, Vazkii noted back in 2016 that he doesn't support optifine: https://github.com/Vazkii/Neat/issues/13. I'm guessing that hasn't changed.

**Comment by Uraneptus** [comment]
I'll leave this open since it's probably still relevant for newer versions. Shader issues are always a bit tricky and thus don't have a high priority, but I'll def look into it again!

**Comment by Uraneptus** [comment]
Looks fine on 1.20.1, tested with 5 different shaders, so I'm closing this
