### ISSUE TITLE
Healthbars grayed out in Enigmatic 2 modpack

### ISSUE THREAD

**Issue by Edwin-Baranov** [VazkiiMods/Neat#37]
In the Enigmatic 2 modpack most health bars ontop of mobs are grayed out along with More Overlay's spawning indicators, here is a Reddit post with an image showing it (https://old.reddit.com/r/MinecraftMod/comments/c83zry/why_is_more_overlays_and_neat_grayed_out/)

**Comment by Deightine** [comment]
Adding in the same problem, but with a custom modpack. 

In my case it is Neat's bar (going gray) and Embers Rekindled's red 'ember' light sources (going white). Both seem to lose their color values or some extra layer of rendering. Not sure why. It doesn't happen in a fresh game, but increases frequency after some play.

**Comment by Goldenlion5648** [comment]
Little late, but I am also having this problem in my custom pack, we can try comparing mods to see what overlaps, here is mine (generated using /ct mods): https://hastebin.com/ekoyogesik.nginx

**Comment by Goldenlion5648** [comment]
It is PSI https://github.com/Vazkii/Psi/issues/525

**Comment by Wolfstar1010** [comment]
I'm having the same/similar issue in a custom modpack. I've narrowed the conflicting mod down to the Locks mod (https://www.curseforge.com/minecraft/mc-mods/locks) for us. The interesting thing for us though, is that the bar is only grayed out when viewing the mob is at a point lower than you and is fine if you are below the mob. It's very oddly specific but here is a photo

![99483948-56b67f80-292d-11eb-8f6f-6c438dfa0668](https://user-images.githubusercontent.com/66505198/99678305-a9d12500-2a48-11eb-8046-0c628ae4f3f9.png)

**Comment by williewillus** [comment]
Was caused by Psi (see above)
