### ISSUE TITLE
Error upon loading into an sp or mp world

### ISSUE THREAD

**Issue by MrExzibit** [VazkiiMods/Neat#48]
For some reason, I receive this error on version 1.15.2 whenever I try to load into either a private mp server with the mod or into my person sp world.

My friend doesn't get any crashes with the same mod configuration.

The error is:

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraftforge.client.event.RenderWorldLastEvent.getProjectionMatrix()Lnet/minecraft/client/renderer/Matrix4f;

My current list of mods
![image](https://user-images.githubusercontent.com/16407673/78250987-8f156480-74e8-11ea-8339-c17a0fcb477e.png)

**Comment by qybust** [comment]
i can open the world with the latest forge,you can try

**Comment by williewillus** [comment]
same as #50
