### ISSUE TITLE
crash report please help

### ISSUE THREAD

**Issue by MinePiece** [VazkiiMods/Neat#49]
Hello everyone, can you help me ?
I never success to open my world with the mod Neat and I don't understand why.
I tried with other mods and with only Neat but the result is still the same : crash report.

I put here my crash report and I hope someone would be able to help me.

[crash-2020-04-04_15.10.45-client.txt](https://github.com/Vazkii/Neat/files/4431409/crash-2020-04-04_15.10.45-client.txt)

**Comment by qybust** [comment]
i also can't open my world with neat.wait repair

**Comment by qybust** [comment]
i can open the world with the latest forge,you can try it
