### ISSUE TITLE
Game is crashing when I try to load into SP

### ISSUE THREAD

**Issue by ketscherblukken** [VazkiiMods/Neat#50]
I'm on minecraft 1.15.2 and I have forge 31.1.0

Whenever I put Neat into my mods folder my game crashes when I try to load into my world and it stops when I take Neat out. 
[crash-2020-04-27_17.25.52-client.txt](https://github.com/Vazkii/Neat/files/4542737/crash-2020-04-27_17.25.52-client.txt)

This is my mod list. 
![2020-04-27 17_37_57-Window](https://user-images.githubusercontent.com/64447204/80434169-e7ecd880-88ad-11ea-8001-df94ee6ea321.png)

**Comment by Mister-Gibus** [comment]
Was told on the discord to contribute to this thread.
https://pastebin.com/v39eMgmV

**Comment by Hubry** [comment]
You must use at least Forge 31.1.19. Blame the guy who ported the mod for not setting the Forge dependency to that. Also why are you using those ancient Forge versions when a new recommended is out? :P

**Comment by nichdel** [comment]
@Hubry I know the log @Mister-Gibus posted here is on an old forge but they also tried it (in #help) on latest forge. @Mister-Gibus Could you post a log of this happening on latest?

**Comment by williewillus** [comment]
assuming this is irrelevant now
