### ISSUE TITLE
[Request] Option to make health bars opaque.

### ISSUE THREAD

**Issue by KodyGW** [VazkiiMods/Neat#51]
I know the mod currently doesn't work with shaders but I've tried other health bar mods that have opaque bars and they seem to work fine with shaders. Maybe the transparency is what's causing the issue?

**Comment by Lyle-Tafoya** [comment]
@FishyFroy I am not the maintainer of this project, but I tried modifying the source to make the health bar opaque and that did not seem to solve the issue. If you can point me in the direction of another health bar mod which doesn't suffer from this issue, it may be possible for me to figure out what they are doing differently.

**Comment by Uraneptus** [comment]
#31
