### ISSUE TITLE
Nametags render a grey background when Overlay Grids from MiniHud are active. 

### ISSUE THREAD

**Issue by rlesch** [VazkiiMods/Neat#55]
Mc version 1.15.2 / forge 31.2.31 / latest optifine pre for 1.15.2 / latest version of neat/minihud for 1.15.2 

- Nametags render a grey background when Overlay Grids from MiniHud are active.

**Comment by Uraneptus** [comment]
If this is still relevant in newer versions of the mod (1.20 onwards), please open a new issue
