### ISSUE TITLE
Nothing is shown above mobs/players when graphics setting is set to Fabulous in 1.16.4

### ISSUE THREAD

**Issue by glang** [VazkiiMods/Neat#64]
I've reproduced this behavior on two PCs. Setting the graphics setting to Fancy fixes it.

**Comment by BugmanBugman** [comment]
Can confirn

**Comment by Vazkii** [comment]
Man why is fabulous such a pain to work with :(

**Comment by williewillus** [comment]
fabulous is fixed in the latest 1.18 build and above
