### ISSUE TITLE
[Suggestion] Disable health bar rendering of mount while riding

### ISSUE THREAD

**Issue by RHSD** [VazkiiMods/Neat#70]
Basically it should not render the health bar of the mount that you are riding. It can be quite intrusive while looking around.

**Comment by darchitectlp** [comment]
I'm using the hotkey to turn off neat whenever I'm on my horse/hippogryph/whatevs, but it'd be really nice to have it auto disappear when the player is riding something.

**Comment by Uraneptus** [comment]
Could be a config option to consider

**Comment by Uraneptus** [comment]
Added
