### ISSUE TITLE
Neat spoils Mimic Chest mobs

### ISSUE THREAD

**Issue by mistaboom** [VazkiiMods/Neat#71]
This is not really a bug but I feel like "Neat" health bars displaying over a lonely chest underground is a dead giveaway for it being a mimic.

**Comment by RainbowSaber** [comment]
Thats why there is a blacklist in the config, just add "artifacts:mimic" and you are fine

**Comment by mistaboom** [comment]
That worked! I should have read the config. Sorry for wasting your time
