### ISSUE TITLE
Game crashes when I look at a mob from Chocolate Quest Reloaded

### ISSUE THREAD

**Issue by andrewduong2001** [VazkiiMods/Neat#72]
[crash-2021-03-24_20.15.37-client.txt](https://github.com/Vazkii/Neat/files/6201846/crash-2021-03-24_20.15.37-client.txt)

It was one of the Enderman NPCs in the Taverns. Not sure what happened, but the screen turned gray with thick white lines in the middle.

**Comment by Zilacon** [comment]
Confirmed to be an issue with me as well. In my case it was a bartender.

**Comment by popo88299** [comment]
Same. When this issue can be fixed...

**Comment by Minghas** [comment]
[crash-2021-06-24_13.19.33-client.txt](https://github.com/Vazkii/Neat/files/6709232/crash-2021-06-24_13.19.33-client.txt)

Same with me, in my case it only happens with the Abyss Walkers and Abyss Walker King

**Comment by ChaosDogG** [comment]
[crash-2022-06-03_14.21.34-client.txt](https://github.com/VazkiiMods/Neat/files/8835848/crash-2022-06-03_14.21.34-client.txt)

Same here, but w the Player Mobs mod

**Comment by Uraneptus** [comment]
If this is still relevant in the newer versions, please open a new issue
