### ISSUE TITLE
[Suggestion] Add option to only show Unit Frames on specific types of entities

### ISSUE THREAD

**Issue by jakey1995abc** [VazkiiMods/Neat#73]
I feel that adding a feature to enable/disable unit frames for specific mob types (for example: passive, neutral, hostile, player, boss) would be a very neat addition to this mod, removing the need to manually add a whole list of blacklisted mobs :)

**Comment by blahpers** [comment]
+1 this.  Players on my server are requesting the ability to disable for, e.g., passive mobs like cows/pigs/chickens so that their ranches arent cluttered with infoplates.

**Comment by Uraneptus** [comment]
Planning on changing how the whole blacklist thing works. I'll add this to the list of things to consider.

**Comment by Uraneptus** [comment]
I added a config option to disable all passive mobs or all hostile mobs. This felt like the best solution, since we already have an option for players and bosses
