### ISSUE TITLE
Neat Keybind is titled incorrectly

### ISSUE THREAD

**Issue by Foozey** [VazkiiMods/Neat#77]
It reads "neat.keybind.toggle" instead of the actual title of the keybind.

**Comment by Foozey** [comment]
The solution to this is renaming your `en_US.json` to just `en_us.json`, the same goes for other languages.

**Comment by williewillus** [comment]
[b2eeae8](https://github.com/VazkiiMods/Neat/commit/b2eeae88eb0ac6c65ffc16d4c5ae21cdb90051ab)
