### ISSUE TITLE
Neat Causes optifine flickering

### ISSUE THREAD

**Issue by Mr-Syntax** [VazkiiMods/Neat#79]
phew this one of the more annoying debuggings ive done, but i can with certainty say that Neat causes optifine rendering artifacts which make the ground see through would be cool if you could fix this

hope this helps alot of other people as ive seen alot of people having those flickering issues, but it was very unintuitive that it was caused by neat

**Comment by JetpackRescue** [comment]
it doesn't cause this for me. sounds like something else is going on.

**Comment by mav-8** [comment]
I have the same issue. If I look at a mob, it flickers. When I move behind a tree and hide the mob from my LOS, it's fine. As soon as I peek out staring at the mob, it flickers again.

**Comment by williewillus** [comment]
Optifine is not supported, sorry. See https://vazkii.notion.site/Violet-Moon-FAQ-ddd80d35a63d4d268396dc09f8f9236e#952e6f328c6b482e98d141a8440da4b2
