### ISSUE TITLE
Feature Request: Font Color configuration option

### ISSUE THREAD

**Issue by AngleWyrm10** [VazkiiMods/Neat#83]
This is probably the result of my shader pack; notice the text is virtually unreadable due to it's color
![neat](https://user-images.githubusercontent.com/55937426/123704130-2e272a00-d81a-11eb-9177-fa649e3608ed.png)

**Comment by Uraneptus** [comment]
Will look st this for the newer versions

**Comment by Uraneptus** [comment]
Added
