### ISSUE TITLE
Turn blacklist into whitelist, name visibility for specific mobs but not others

### ISSUE THREAD

**Issue by JetpackRescue** [VazkiiMods/Neat#87]
I would like the ability for a modpack to turn the blacklist into a whitelist so I don't have to add hundreds of mobs if I only want the villagers to have name tags. 

The ability to hide or show names based on a whitelist and blacklist.

I want mobs to show what health they have but not show their names, but I only want the villagers to have their nametags.

**Comment by Uraneptus** [comment]
I will def add something to make blacklisting mobs easier. Adding a whitelist switch could be one of the ideas.
However I probably won't add the name visibility feature you mentioned
