### ISSUE TITLE
[1.18.1] modpack crash when mobs in range

### ISSUE THREAD

**Issue by Bass2style** [VazkiiMods/Neat#89]
Hi,

the game is crashing when a mob that the "bar should be visible" come in range, mostly hostiles ones apparently. (git issues with creepers, zombies, and apparently endermans, but sheeps etc seems not problematic)

here is a crashlog on a "basic mods" pack, with jmap, jei, and some other soft mods : https://gist.github.com/Bass2style/f079bd996700163472b1da405bfaebe7
and one of my bigger modpack : https://gist.github.com/Bass2style/baf26645eff954af57bff4a0dd6becbd
another one for the same pack, but Neat doesn't appair in the crash report : https://gist.github.com/Bass2style/7c38e549cc0f16d9efb6453eb1583643

i removed Neat from my pack, and everything seems working without issues.

have a nice day.

**Comment by koza1258** [comment]
Hi,
I had exactly the same. The worst thing is that there is nothing in the logs, or if it is something else.

2 hours taken out of life looking for why the package stopped working: p

https://gist.github.com/koza1258/afca7f0ec6775aaa0dae68b01d383a85

**Comment by coldReactive** [comment]
Bees will guarantee this crash will happen on spawning or leaving bees nests if the bee nest spawns with bees inside.
