### ISSUE TITLE
1.18.1 crash when world loads

### ISSUE THREAD

**Issue by ffuentesm** [VazkiiMods/Neat#90]
When I try to load the world I get this error. 

NullPointerException: Cannot invoke "net.minecraft.client.renderer.ShaderInstance.m_173350_(String, Object)" because "$$13" is null

https://crashy.net/al5a4O58Cf20f24iHEkc

**Comment by coldReactive** [comment]
Same Issue: https://github.com/VazkiiMods/Neat/issues/89

**Comment by williewillus** [comment]
^
