### ISSUE TITLE
[1.18.1] Crash when quark shiba healthbar is rendered

### ISSUE THREAD

**Issue by thelegitdolt** [VazkiiMods/Neat#92]
crash report: https://gist.github.com/thelegitdolt/e9117bb6d9916d40639e457e9da508a9

latest.log: https://gist.github.com/thelegitdolt/fcf3bc600768a4bc94ef3772e2f9e4ca

**Comment by thelegitdolt** [comment]
might be issue with quark i have no clue

**Comment by thelegitdolt** [comment]
sorry

**Comment by coldReactive** [comment]
Probably same issue as https://github.com/VazkiiMods/Neat/issues/89

**Comment by thelegitdolt** [comment]
not getting crashes anymore after updating
