### ISSUE TITLE
Zombies cause 1.18.1 Version to Crash

### ISSUE THREAD

**Issue by ummjonny** [VazkiiMods/Neat#98]
I was wondering why my game was crashing until I looked at the crash log and it said something was wrong with loading zombies. 

I tried to spawn a zombie into my game with this mod on and the game crashed.

When I took off this mod and spawned a zombie, the game did not crash.

I downloaded the latest 1.18.1 Version from curseforge

**Comment by williewillus** [comment]
please try with the latest version now
