### ISSUE TITLE
Relicense the code

### ISSUE THREAD

**Issue by williewillus** [VazkiiMods/Neat#99]
The code is under the CC license, which is generally seen as a bad license for code.

There's only a handful of meaningful contributors to this mod so, unlike Patchouli or Botania, a relicense of the code to a better license (MIT, probably) is actually feasible. Assets and lang files will keep their current CC license.

This issue is just a reminder for me to gather the ~5 people whose approval I need to relicense the code.

**Comment by williewillus** [comment]
Here are the people I need, generated from the commit logs.

Just leave a comment saying "I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT"

- @Vazkii 
- @Alwinfy 
- @GirafiStudios 
- @Kamefrede 
- @Vaelzan 
- @williewillus 
- @Insane96 

Code contributions were also made by the following people, but their changes have since been completely deleted or rewritten, meaning no approval is necessary:

- @Rover656 - Made contributions to the mods.toml and build script, both of which have been naturally superseded with newer values with new Minecraft versions.
- @loordgek - Changed the @Mod line to add clientSideOnly, a feature no longer present in modern Forge versions.

All remaining committers as of the time of writing contributed only to translation files, which will keep their current CC license. No approval is necessary.

**Comment by williewillus** [comment]
I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT

**Comment by Vaelzan** [comment]
I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT

**Comment by Insane96** [comment]
I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT

**Comment by Kamefrede** [comment]
I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT

**Comment by GirafiStudios** [comment]
I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT

**Comment by Alwinfy** [comment]
I agree to relicense my code contributions to Neat from CC BY-NC-SA to MIT
